-- DROP TABLE IF EXISTS TB_PRODUTOS;
-- CREATE TABLE TB_PRODUTOS(
--     ID_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
--     NOME_PRODUTO TEXT NOT NULL,
--     DESCRICAO TEXT NOT NULL,
--     PRECO DECIMAL(10,2) NOT NULL,
--     QUANTIDADE INT NOT NULL,
--     CATEGORIA TEXT NOT NULL
-- )

-- --create

-- INSERT INTO TB_PRODUTOS 
--     (NOME_PRODUTO, DESCRICAO, PRECO, QUANTIDADE, CATEGORIA)
-- VALUES
--     ('Camisa Azul', 'GG', 49.90, 20, 'Casual'),
--     ('Camisa Vermelha', 'M', 39.90, 20, 'Casual')

-- --read
-- SELECT * FROM TB_PRODUTOS

-- --update
-- UPDATE TB_PRODUTOS
-- SET NOME_PRODUTO = 'Camisa Azul',
--     DESCRICAO = 'PP',
--     PRECO = 49.90,
--     QUANTIDADE = 05,
--     CATEGORIA = 'Casual'
-- WHERE ID_PRODUTO = 1

-- --delete
-- DELETE FROM TB_PRODUTOS WHERE ID = 1;
